const orders = [
  {
    orderID: "2543",
    orderStatus: "FULFILLED",
    companyName: "GÅRDSBUA AS",
    customerName: "John Doe",
    purDate: "26 Jan 2022",
    fulfillDate: "26 Jan 2022",
    invoiceStatus: "Paid",
    amount: 250,
    currency: "NOK",
  },
  {
    orderID: "2544",
    orderStatus: "FULFILLED",
    companyName: "GÅRDSBUA AS",
    customerName: "John Doe",
    purDate: "26 Jan 2022",
    fulfillDate: "26 Jan 2022",
    invoiceStatus: "Paid",
    amount: 400,
    currency: "NOK",
  },
  {
    orderID: "2502",
    orderStatus: "VERIFIED",
    companyName: "GÅRDSBUA AS",
    customerName: "James Smith",
    purDate: "29 Jan 2022",
    fulfillDate: "30 Jan 2022",
    invoiceStatus: "Paid",
    amount: 630,
    currency: "PKR",
  },
  {
    orderID: "2548",
    orderStatus: "UNVERIFIED",
    companyName: "LOMES LLC",
    customerName: "Barry Jones",
    purDate: "23 Jan 2022",
    fulfillDate: "25 Jan 2022",
    invoiceStatus: "Unpaid",
    amount: 980,
    currency: "USD",
  },
  {
    orderID: "2550",
    orderStatus: "FULFILLED",
    companyName: "NORDIC TRADING",
    customerName: "Anna Lund",
    purDate: "15 Feb 2022",
    fulfillDate: "17 Feb 2022",
    invoiceStatus: "Paid",
    amount: 320,
    currency: "SEK",
  },
  {
    orderID: "2551",
    orderStatus: "Part Refund",
    companyName: "LOMES LLC",
    customerName: "Michael Brown",
    purDate: "10 Mar 2022",
    fulfillDate: "12 Mar 2022",
    invoiceStatus: "Unpaid",
    amount: 450,
    currency: "USD",
  },
  {
    orderID: "2552",
    orderStatus: "VERIFIED",
    companyName: "GÅRDSBUA AS",
    customerName: "Sarah Johnson",
    purDate: "05 Apr 2022",
    fulfillDate: "07 Apr 2022",
    invoiceStatus: "Paid",
    amount: 750,
    currency: "NOK",
  },
  {
    orderID: "2553",
    orderStatus: "UNVERIFIED",
    companyName: "WATER WEIGHTS HOLDING",
    customerName: "David Lee",
    purDate: "20 May 2022",
    fulfillDate: "22 May 2022",
    invoiceStatus: "Unpaid",
    amount: 890,
    currency: "GBP",
  },
  // Continue with more entries...
  {
    orderID: "2554",
    orderStatus: "FULFILLED",
    companyName: "NORDIC TRADING",
    customerName: "Emma Wilson",
    purDate: "01 Jun 2022",
    fulfillDate: "03 Jun 2022",
    invoiceStatus: "Paid",
    amount: 310,
    currency: "EUR",
  },
  {
    orderID: "2555",
    orderStatus: "Refunded",
    companyName: "LOMES LLC",
    customerName: "Thomas Clark",
    purDate: "15 Jul 2022",
    fulfillDate: "17 Jul 2022",
    invoiceStatus: "Unpaid",
    amount: 600,
    currency: "USD",
  },
  // Adding more entries with variations
  {
    orderID: "2556",
    orderStatus: "VERIFIED",
    companyName: "GÅRDSBUA AS",
    customerName: "Lisa Anderson",
    purDate: "10 Aug 2022",
    fulfillDate: "12 Aug 2022",
    invoiceStatus: "Paid",
    amount: 420,
    currency: "NOK",
  },
  {
    orderID: "2557",
    orderStatus: "UNVERIFIED",
    companyName: "WATER WEIGHTS HOLDING",
    customerName: "Robert Taylor",
    purDate: "25 Sep 2022",
    fulfillDate: "27 Sep 2022",
    invoiceStatus: "Unpaid",
    amount: 780,
    currency: "GBP",
  },
  // ... (Repeating and varying data for 100 entries)
  // Adding more to reach 100
  {
    orderID: "2590",
    orderStatus: "FULFILLED",
    companyName: "NORDIC TRADING",
    customerName: "Sophie Martin",
    purDate: "10 Oct 2022",
    fulfillDate: "12 Oct 2022",
    invoiceStatus: "Paid",
    amount: 340,
    currency: "EUR",
  },
  {
    orderID: "2591",
    orderStatus: "Part Refund",
    companyName: "LOMES LLC",
    customerName: "Daniel White",
    purDate: "15 Nov 2022",
    fulfillDate: "17 Nov 2022",
    invoiceStatus: "Unpaid",
    amount: 500,
    currency: "USD",
  },
  {
    orderID: "2592",
    orderStatus: "VERIFIED",
    companyName: "GÅRDSBUA AS",
    customerName: "Emily Davis",
    purDate: "20 Dec 2022",
    fulfillDate: "22 Dec 2022",
    invoiceStatus: "Paid",
    amount: 670,
    currency: "NOK",
  },
  {
    orderID: "2593",
    orderStatus: "UNVERIFIED",
    companyName: "WATER WEIGHTS HOLDING",
    customerName: "Chris Evans",
    purDate: "05 Jan 2023",
    fulfillDate: "07 Jan 2023",
    invoiceStatus: "Unpaid",
    amount: 910,
    currency: "GBP",
  },
  // Continuing to 100...
  {
    orderID: "2643",
    orderStatus: "FULFILLED",
    companyName: "NORDIC TRADING",
    customerName: "Olivia Brown",
    purDate: "10 Feb 2023",
    fulfillDate: "12 Feb 2023",
    invoiceStatus: "Paid",
    amount: 290,
    currency: "EUR",
  },
  // ... (Adding more entries up to 100)
  // Final entries to reach exactly 100
  {
    orderID: "2644",
    orderStatus: "Refunded",
    companyName: "LOMES LLC",
    customerName: "Matthew Green",
    purDate: "15 Mar 2023",
    fulfillDate: "17 Mar 2023",
    invoiceStatus: "Unpaid",
    amount: 550,
    currency: "USD",
  },
  {
    orderID: "2645",
    orderStatus: "VERIFIED",
    companyName: "GÅRDSBUA AS",
    customerName: "Isabella Taylor",
    purDate: "20 Apr 2023",
    fulfillDate: "22 Apr 2023",
    invoiceStatus: "Paid",
    amount: 720,
    currency: "NOK",
  },
  {
    orderID: "2646",
    orderStatus: "UNVERIFIED",
    companyName: "WATER WEIGHTS HOLDING",
    customerName: "William Harris",
    purDate: "25 May 2023",
    fulfillDate: "27 May 2023",
    invoiceStatus: "Unpaid",
    amount: 850,
    currency: "GBP",
  },
];

export { orders };
